"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载项目根目录 .env（与 Flask 重排序微服务共用同一配置）
env_path = BASE_DIR.parent / '.env'
print(f"正在加载环境变量文件: {env_path}")
print(f"文件是否存在: {env_path.exists()}")

load_dotenv(env_path)

DASHSCOPE_API_KEY = os.getenv('DASHSCOPE_API_KEY')
print(f"API Key 是否加载: {'是' if DASHSCOPE_API_KEY else '否'}")

# RAG 相关配置
CHROMA_DB_PATH = os.getenv("CHROMA_DB_PATH", str(BASE_DIR / "chroma_db"))
TMP_DIR = str(BASE_DIR / "tmp")

# 重排序配置
# RERANKER_USE_LOCAL: True 使用本地 bge-reranker-large 模型（默认）；False 调用远程 DashScope API
RERANKER_USE_LOCAL = os.getenv("RERANKER_USE_LOCAL", "True").lower() in ("true", "1", "yes")
# RERANKER_MODEL_PATH: 本地模型路径，默认为项目目录下的 backend/models/bge-reranker-large
RERANKER_MODEL_PATH = os.getenv(
    "RERANKER_MODEL_PATH",
    str(BASE_DIR / "models" / "bge-reranker-large")
)
# 远程重排序微服务地址（仅当 RERANKER_USE_LOCAL=False 时使用）
RERANK_SERVICE_URL = os.getenv("RERANK_SERVICE_URL", "http://127.0.0.1:5001/rerank")

# 本地嵌入模型路径（向量化用，bge-large-zh）
LOCAL_EMBEDDING_MODEL = os.getenv(
    "LOCAL_EMBEDDING_MODEL",
    str(BASE_DIR / "models" / "bge-large-zh")
)

# 检索与拒答阈值配置
# RRF 分数通常在 0~0.2 左右；达到该值视为可用上下文，否则拒答。
RAG_RELEVANCE_THRESHOLD = float(os.getenv("RAG_RELEVANCE_THRESHOLD", "0.04"))
# CrossEncoder 原始分数达到该值视为相关，走 RAG 模板。
RAG_CE_RELEVANCE_THRESHOLD = float(os.getenv("RAG_CE_RELEVANCE_THRESHOLD", "0.3"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY = os.getenv('SECRET_KEY')
if not _SECRET_KEY:
    import warnings
    from django.core.management.utils import get_random_secret_key
    _SECRET_KEY = get_random_secret_key()
    warnings.warn(
        "!!! 环境变量 SECRET_KEY 未设置，已自动生成临时随机值。"
        "生产环境必须通过环境变量设置固定的 SECRET_KEY，否则每次重启后用户会话将失效。"
    )
SECRET_KEY = _SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'chunker_api.apps.ChunkerApiConfig',  # ✅ 关键：启用 ready() 预热
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = 'static/'

# Media files（图片/上传文件）
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 提取图片目录（/api/media/<path> 读取此目录下文件）
EXTRACTED_IMAGES_DIR = MEDIA_ROOT / 'extracted_images'


# Default primary key field type

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ 关键：指定使用自定义的用户模型，解决 E304 冲突
AUTH_USER_MODEL = 'chunker_api.User'

