# Generated by Django 5.2.7 on 2025-11-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker_api', '0002_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_enterprise_user',
            field=models.BooleanField(default=False, verbose_name='是否为企业用户'),
        ),
    ]
