# Generated by Django 5.2.7 on 2025-11-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker_api', '0003_user_is_enterprise_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_enterprise_user',
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='工号'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('personal', '个人用户'), ('enterprise', '企业用户')], default='personal', max_length=20, verbose_name='用户类型'),
        ),
    ]
