# Generated by Django 5.2.7 on 2026-01-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker_api', '0004_remove_user_is_enterprise_user_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='trace_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='追踪ID'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, null=True, verbose_name='引用来源（文档级静态信息）'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='retrieval_hits',
            field=models.JSONField(blank=True, null=True, verbose_name='检索命中（chunk级动态信息）'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='evidence_spans',
            field=models.JSONField(blank=True, null=True, verbose_name='证据片段'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='retrieval_stats',
            field=models.JSONField(blank=True, null=True, verbose_name='检索统计'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='refusal',
            field=models.JSONField(blank=True, null=True, verbose_name='拒答信息'),
        ),
    ]
