# Generated by Django 6.0.6 on 2026-06-30 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chunker_api", "0006_chatmessage_suggested_next_questions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="用户名"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("SUPER_ADMIN", "超级管理员"),
                            ("KB_ADMIN", "知识库管理员"),
                        ],
                        default="KB_ADMIN",
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "系统管理员",
                "verbose_name_plural": "系统管理员",
                "db_table": "admin_users",
            },
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="status",
            field=models.CharField(
                choices=[("active", "运行中"), ("inactive", "已禁用")],
                default="active",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "已启用"),
                            ("inactive", "已禁用"),
                            ("deleted", "已删除"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="文档状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "knowledge_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="chunker_api.knowledgebase",
                        verbose_name="所属知识库",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识库文档",
                "verbose_name_plural": "知识库文档",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="物理存储路径"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="分块数量"),
                ),
                (
                    "embedding_count",
                    models.PositiveIntegerField(default=0, verbose_name="向量化数量"),
                ),
                (
                    "chunker_type",
                    models.CharField(
                        default="semantic", max_length=50, verbose_name="分块器类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "当前主版本"), ("historical", "历史版本")],
                        default="historical",
                        max_length=20,
                        verbose_name="版本状态",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="备注说明"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="chunker_api.document",
                        verbose_name="所属逻辑文档",
                    ),
                ),
                (
                    "uploaded_by_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chunker_api.adminuser",
                        verbose_name="上传管理员(后台)",
                    ),
                ),
                (
                    "uploaded_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户(前台)",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "ordering": ["-version_number"],
                "unique_together": {("document", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.TextField(verbose_name="用户提问快照")),
                ("answer", models.TextField(verbose_name="模型回答快照")),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("ANSWER_ERROR", "回答错误"),
                            ("HALLUCINATION", "幻觉内容"),
                            ("DOCUMENT_OUTDATED", "内容过期"),
                            ("RETRIEVAL_ERROR", "引用错误"),
                            ("OTHER", "其他"),
                        ],
                        max_length=50,
                        verbose_name="反馈类型",
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(blank=True, null=True, verbose_name="用户备注"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("RESOLVED", "已解决"),
                            ("IGNORED", "已忽略"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "handler",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_feedbacks",
                        to="chunker_api.adminuser",
                        verbose_name="处理人",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chunker_api.chatmessage",
                        verbose_name="关联消息",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="chunker_api.chatsession",
                        verbose_name="关联会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户反馈",
                "verbose_name_plural": "用户反馈",
                "db_table": "feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeedbackChunk",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("chunk_id", models.CharField(max_length=255, verbose_name="Chunk ID")),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="Chunk内容快照"
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="检索分数"),
                ),
                (
                    "rank",
                    models.IntegerField(blank=True, null=True, verbose_name="检索排名"),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_chunks",
                        to="chunker_api.feedback",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_chunk",
            },
        ),
        migrations.CreateModel(
            name="FeedbackDocument",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chunker_api.document",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chunker_api.documentversion",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_documents",
                        to="chunker_api.feedback",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_document",
            },
        ),
        migrations.CreateModel(
            name="FeedbackProcessLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_OFFLINE", "下架文档"),
                            ("CHUNK_UPDATED", "更新Chunk"),
                            ("DOCUMENT_REPUBLISHED", "重新发布文档"),
                            ("IGNORED", "忽略反馈"),
                            ("STATUS_CHANGED", "状态变更"),
                        ],
                        max_length=50,
                    ),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_logs",
                        to="chunker_api.feedback",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chunker_api.adminuser",
                    ),
                ),
            ],
            options={
                "db_table": "feedback_process_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action", models.CharField(max_length=50, verbose_name="操作类型")),
                ("details", models.TextField(verbose_name="详细描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chunker_api.adminuser",
                        verbose_name="操作管理员",
                    ),
                ),
            ],
            options={
                "db_table": "operation_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
