# Generated by Django 6.0.6 on 2026-07-01 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chunker_api", "0007_adminuser_knowledgebase_status_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("enterprise", "企业用户"),
                            ("external", "外来用户"),
                            ("local", "本地居民"),
                        ],
                        default="external",
                        max_length=20,
                        verbose_name="用户角色",
                    ),
                ),
                (
                    "age_group",
                    models.CharField(
                        choices=[("youth", "青年"), ("elder", "老年")],
                        default="youth",
                        max_length=10,
                        verbose_name="年龄段",
                    ),
                ),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("active_days", models.PositiveIntegerField(default=0)),
                ("last_active_date", models.DateField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("new", "新用户"),
                            ("normal", "普通用户"),
                            ("high", "高频用户"),
                        ],
                        default="new",
                        max_length=10,
                        verbose_name="活跃度",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户画像",
                "verbose_name_plural": "用户画像",
                "db_table": "user_personas",
            },
        ),
    ]
